### ISSUE TITLE
Multiple object editing problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/chise.js#57] opened 2016-09-26 11:37 UTC
When you select multiple objects and try to edit their properties (e.g. dimensions), not all are properly set. Besides, the newly set value is not shown in the inspector.

**Comment by metincansiper** [comment] 2016-09-26 12:52
It seems that the problem related to "the newly set value is not shown in the inspector" is fixed now. However, I could not reproduce the other problem.

**Closed** 2016-09-26 16:56 UTC
Labels: Critical
